"""create_handoff.py — 단일 Markdown 인계 번들 생성 (Phase 1).

.ai/handoffs/handoff_<timestamp>.md 를 생성한다.
- 현재 상태 (CURRENT.md)
- 변경 사항 (Git status, diff stat)
- 테스트 결과 (ledger 의 최근 종료 서명)
- 블로커, 다음 작업, 롤백 지점, 알려진 제한
- 민감정보는 마스킹된다 (원문 미출력)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import (  # noqa: E402
    GitError,
    changed_files,
    configure_utf8_io,
    deleted_files,
    git_branch,
    git_head,
    git_status_porcelain,
    is_git_repo,
    mask_sensitive,
    now_iso,
    read_ledger,
    repo_root,
    resolve_workspace,
    run_git,
    untracked_files,
)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def _diff_stat_lines(workspace: Path) -> list[str]:
    try:
        return run_git(workspace, ["diff", "--stat"]).splitlines()
    except GitError:
        return []


def _latest(entries: list[dict], kind: str) -> dict | None:
    return next((e for e in reversed(entries) if e.get("kind") == kind), None)


def create_handoff(workspace: Path, out: str | None = None) -> dict:
    """인계 번들 마크다운을 생성하고 생성 경로를 반환한다."""
    if not is_git_repo(workspace):
        raise GitError(f"not a Git repository: {workspace}")
    root = repo_root(workspace)
    entries = read_ledger(workspace)
    latest_start = _latest(entries, "start")
    latest_end = _latest(entries, "end")

    current_md = _read_text(root / ".ai" / "CURRENT.md")
    status_md = _read_text(root / ".ai" / "STATUS.md")
    changed = changed_files(workspace)
    untracked = untracked_files(workspace)
    deleted = deleted_files(workspace)
    diff_stat = _diff_stat_lines(workspace)

    if latest_end:
        test_section = (
            "## 4. Test results (last end signature)\n"
            f"- run_id: `{latest_end.get('run_id', '-')}`  status: `{latest_end.get('status', '-')}`\n"
            f"- tests_run: `{latest_end.get('tests_run', '-')}`  passed: `{latest_end.get('tests_passed', '-')}`  "
            f"failed: `{latest_end.get('tests_failed', '-')}`"
        )
    else:
        test_section = "## 4. Test results\n- NOT_RUN (no end signature/test result recorded yet)"

    sections = [
        "# AI Session Handoff Bundle",
        f"> generated: `{now_iso()}`  |  auto-generated by: `scripts/create_handoff.py`\n"
        "> This document is a handoff bundle built so the next AI can pick up the work without any prior conversation.",
        "## 1. Overview\n"
        f"- branch: `{git_branch(workspace)}`\n"
        f"- HEAD: `{git_head(workspace)}`\n"
        f"- working tree: {len(changed)} change(s) (new {len(untracked)} / deleted {len(deleted)})",
        "## 2. Current state (CURRENT.md)\n```markdown\n" + (current_md or "(no CURRENT.md)") + "\n```",
        "## 3. Changes\n"
        + ("- changed/new/deleted files:\n" + "".join(f"  - {p}\n" for p in changed) if changed else "- no changes")
        + ("\n```text\n" + "\n".join(diff_stat) + "\n```" if diff_stat else ""),
        test_section,
        "## 5. Blockers\n"
        + (f"- {latest_end.get('known_issues')}" if latest_end and latest_end.get("known_issues") else "- none (per record)"),
        "## 6. Next steps\n"
        + (f"- {latest_end.get('remaining_work')}" if latest_end and latest_end.get("remaining_work")
           else "- see the handoff notes in CURRENT.md."),
        "## 7. Rollback point\n"
        + (f"- {latest_end.get('rollback_point')}" if latest_end and latest_end.get("rollback_point")
           else f"- last known-good commit: `{git_head(workspace)}`"),
        "## 8. Known limitations\n"
        + (f"- {latest_end.get('known_issues')}" if latest_end and latest_end.get("known_issues") else "- none recorded"),
        "## 9. Status table (STATUS.md)\n```markdown\n" + (status_md or "(no STATUS.md)") + "\n```",
        "## 10. Verification\n"
        "- This bundle reflects the actual Git state at the time it was generated.\n"
        "- Sensitive information is masked. The ledger and the files under .ai/ are the source of truth over signatures, checkpoints, and test results.",
    ]
    body = mask_sensitive("\n\n---\n\n".join(sections)) + "\n"

    ts = now_iso().replace(":", "-").replace("+", "Z")
    out_path = Path(out) if out else root / ".ai" / "handoffs" / f"handoff_{ts}.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body, encoding="utf-8")
    return {"path": str(out_path), "lines": len(body.splitlines())}


def main(argv: list[str] | None = None) -> int:
    configure_utf8_io()
    parser = argparse.ArgumentParser(prog="create_handoff", description="Generate an AI handoff bundle")
    parser.add_argument("--out", default=None, help="output path (default: .ai/handoffs/handoff_<ts>.md)")
    parser.add_argument("--workspace", default=None, help="workspace path (default: current directory)")
    args = parser.parse_args(argv)
    try:
        result = create_handoff(resolve_workspace(args.workspace), out=args.out)
    except GitError as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1
    print(f"handoff: {result['path']} ({result['lines']} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
